name: Output Issue Information
on: issues
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output GitHub Issue Event Context
              run: echo "${{ toJSON(github.event) }}"